var pkg = require('../package.json');

/* Setup: Initial values from banner boilerplate
--------------------------------------------------------------------------- */
var defaults = {
    name: 'client-name', // YY-aaa-9999 (e.g. 15-car-7155); view README.md for formatting
    title: '{{Project Title}}', // Will be used on the review page template
    folder: '_banner-template', // starter boilerplate to build banners
    zipFolder: 'zip-folder', // name of folder containing zip files,
    zipFolderSizeLimit: 200 * 1000, // IAB filesize limit is 200KB; 1000 used for physical disk sizes; see: http://stackoverflow.com/a/8632634
    zipFolderExceedFlag: 'error', // `error` or `warn`; stop on `error`, continue on `warn`
    css_header: '/* Do not edit this file directly. Update styles in `source.css` only.\n' + Array(75).join('=') + ' */\n\n'
};

/* Setup: Project Formatting
--------------------------------------------------------------------------- */
var project = {
    year: pkg.name.split('-')[0],
    clientCode: pkg.name.split('-')[1].toUpperCase(),
    jobCode: pkg.name.split('-')[2],
    get name() {
        return this.year + this.clientCode + this.jobCode;
    },
    get title() {
        return this.clientCode + ' ' + this.jobCode + ' ' + pkg.title;
    },
    review_template: 'https://github.com/misega/HTML5-Banners-Review-Site'
};

/* Setup: File paths
--------------------------------------------------------------------------- */
var paths = {
    html: '/index.html',
    img: '/assets/img/**/*',
    css: {
        source: '/assets/css/source.css',
        destination: '/assets/css/'
    },
    js: '/assets/js/*.js'
};

/* Setup: Folders for distribution
--------------------------------------------------------------------------- */
var folder = {
    review: '_review',
    deploy: '_deploy',
    ad_platform: './banners/_banner-support-files/ad-platform/'
};

/*
--------------------------------------------------------------------------- */
module.exports = {
    pkg: pkg,
    defaults: defaults,
    project: project,
    paths: paths,
    folder: folder,
    watchFolder: '',
    injectAdPlatform: false,
    sizeRegExp: new RegExp('(\\d{2,}x\\d{2,})', 'g')
};
